apiVersion: v1
kind: Pod
metadata:
  name: snowflake-app
  labels:
    app: snowflake-app
spec:
  containers:
    - name: snowflake-app
      image: snowflake-app
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  restartPolicy: Always

